---
# Common variables for all hosts
# All variables are documented with type, default, and description.

# Base directory for Mailu configuration and data on the target host
mailu_base_dir: /opt/mailu

# Target system user for file ownership and service management
# Type: string
# Default: "mailu" (secure, production-ready default)
# This user will own Mailu files, directories, and run Mailu-related services.
# Override per host or group in inventory or host_vars/group_vars as needed.
# Example (in inventory/hosts):
#   mail.example.com ansible_user=operations target_user=operations
# Example (in group_vars/operations.yml):
#   target_user: operations
#
target_user: mailu

# System timezone
# Type: string
# Default: "UTC"
timezone: UTC

# Ansible SSH connection user (can also be set in inventory)
# Type: string
# Default: "mailu"
# This is the user Ansible will use to connect via SSH.
# Override per host or group in inventory or host_vars/group_vars as needed.
# Example (in inventory/hosts):
#   mail.example.com ansible_user=conan_the_deployer
ansible_user: mailu

# Version pins for all core components
mailu_version: "1.9.2"           # Mailu version to deploy
traefik_version: "2.9.8"         # Traefik version
crowdsec_version: "1.5.2"        # CrowdSec version
backup_version: "1.0.0"          # Backup scripts version (if applicable)
docker_version: "24.0.7"         # Docker Engine version
docker_compose_version: "2.21.0" # Docker Compose version

# Traefik configuration
traefik_network_name: traefik_proxy
traefik_config_dir: "{{ mailu_base_dir }}/traefik"
traefik_acme_email: "admin@example.com" # Email for Let's Encrypt registration

# Cloudflare API credentials (will be loaded from vault)
# cloudflare_api_token: "{{ vault_cloudflare_api_token }}"
cloudflare_api_email: "admin@example.com" # Cloudflare account email (if using API key)

# SSH hardening settings
ssh_port: 22
ssh_allowed_users:
  - "{{ target_user }}"
  - "{{ ansible_user }}"

# Mail security defaults
mail_dmarc_policy: "reject"      # DMARC policy (none, quarantine, reject)
mail_spf_policy: "-all"          # SPF policy (~all or -all)
mail_dkim_key_size: 2048          # DKIM key size

# Resource limits for containers
mailu_smtp_memory: "512M"
mailu_smtp_cpu: "0.5"
mailu_imap_memory: "1G"
mailu_imap_cpu: "1.0"

# CrowdSec settings
crowdsec_enabled: true

# Health checks and monitoring
health_check_enabled: true
health_check_interval: 5m # Format for cron job

# Ntfy notification settings
ntfy_enabled: false # Set to true to enable notifications
ntfy_url: https://ntfy.sh # Change to your self-hosted instance if needed
ntfy_topic: "mailu-alerts" # Topic name to use for notifications
ntfy_send_success: false # Whether to send notifications on successful health checks
# ntfy_auth_token: "{{ vault_ntfy_auth_token }}" # Optional auth token if your ntfy instance requires authentication
mailu_debug: false # Set to true for verbose debugging output
