---
# Monitoring role default variables

# General monitoring settings
monitoring_enabled: true
monitoring_base_dir: /opt/monitoring
monitoring_data_dir: "{{ monitoring_base_dir }}/data"

# Prometheus configuration
prometheus_enabled: true
prometheus_version: "v2.46.0"
prometheus_config_dir: "{{ monitoring_base_dir }}/prometheus"
prometheus_data_dir: "{{ monitoring_data_dir }}/prometheus"
prometheus_retention_time: "15d"
prometheus_scrape_interval: "15s"
prometheus_evaluation_interval: "15s"
prometheus_port: 9090

# Node exporter configuration
node_exporter_enabled: true
node_exporter_version: "1.6.1"
node_exporter_port: 9100

# Mailserver exporters
postfix_exporter_enabled: true
postfix_exporter_version: "0.3.0"
postfix_exporter_port: 9154
postfix_exporter_log_dir: "/var/log"

dovecot_exporter_enabled: true
dovecot_exporter_version: "0.1.3"
dovecot_exporter_port: 9166

redis_exporter_enabled: true
redis_exporter_version: "1.50.0"
redis_exporter_port: 9121

# Blackbox exporter for external endpoint checks
blackbox_exporter_enabled: true
blackbox_exporter_version: "0.24.0"
blackbox_exporter_port: 9115

# Grafana configuration
grafana_enabled: true
grafana_version: "10.0.3"
grafana_port: 3000
grafana_config_dir: "{{ monitoring_base_dir }}/grafana"
grafana_data_dir: "{{ monitoring_data_dir }}/grafana"
grafana_admin_user: admin
grafana_admin_password_var: "vault_grafana_admin_password"
grafana_anonymous_enabled: false
grafana_smtp_enabled: true
grafana_smtp_host: "localhost:25"
grafana_smtp_from_address: "grafana@{{ primary_domain }}"
grafana_smtp_from_name: "Grafana Alert"

# Alert manager configuration
alertmanager_enabled: true
alertmanager_version: "0.26.0"
alertmanager_config_dir: "{{ monitoring_base_dir }}/alertmanager"
alertmanager_data_dir: "{{ monitoring_data_dir }}/alertmanager"
alertmanager_port: 9093

# Integration with ntfy for alerts
alertmanager_ntfy_enabled: "{{ ntfy_enabled | default(false) }}"
alertmanager_ntfy_url: "{{ ntfy_url | default('') }}"
alertmanager_ntfy_topic: "{{ ntfy_topic | default('alerts') }}"
alertmanager_ntfy_auth_token_var: "vault_ntfy_auth_token"

# Docker container network
monitoring_network_name: monitoring_net

# Security settings
monitoring_expose_ui: false  # Set to true to expose UIs through Traefik
monitoring_basic_auth_enabled: true
monitoring_basic_auth_user: monitor
monitoring_basic_auth_password_var: "vault_monitor_password"

# Log management with Loki
loki_enabled: true
loki_version: "2.9.1"
loki_config_dir: "{{ monitoring_base_dir }}/loki"
loki_data_dir: "{{ monitoring_data_dir }}/loki"
loki_port: 3100
loki_retention_period: "744h"  # 31 days

# Log shipping with Promtail
promtail_enabled: true
promtail_version: "2.9.1"
promtail_config_dir: "{{ monitoring_base_dir }}/promtail"
promtail_port: 9080