---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: mailu-test
    image: ubuntu:22.04
    pre_build_image: true
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: "/sbin/init"
    capabilities:
      - SYS_ADMIN
    tmpfs:
      - /tmp
      - /run
      - /run/lock
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        mailu_base_dir: /opt/mailu
        traefik_config_dir: /opt/traefik/config
        traefik_network_name: traefik_network
        health_check_enabled: false
        crowdsec_enabled: false
        ntfy_enabled: false
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint
scenario:
  name: default
  test_sequence:
    - lint
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - destroy