---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: backup-test
    image: ubuntu:22.04
    pre_build_image: true
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: "/sbin/init"
    capabilities:
      - SYS_ADMIN
    tmpfs:
      - /tmp
      - /run
      - /run/lock
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        mailu_base_dir: /opt/mailu
        backup_base_dir: /opt/mailu/backups
        backup_tmp_dir: /opt/mailu/backups/tmp
        backup_archive_dir: /opt/mailu/backups/archives
        backup_encryption_enabled: true
        backup_encryption_key_var: "BACKUP_ENCRYPTION_KEY"
        backup_rsync_enabled: false
        backup_aws_enabled: false
        backup_azure_enabled: false
        backup_gcp_enabled: false
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint
scenario:
  name: default
  test_sequence:
    - lint
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - destroy