---
# tasks file for dns_management role

- name: Create DNS records directory
  ansible.builtin.file:
    path: "{{ dns_records_dir }}"
    state: directory
    mode: '0755'

- name: Get server public IP address
  ansible.builtin.uri:
    url: "https://api.ipify.org"
    return_content: yes
  register: public_ip_reg
  delegate_to: localhost
  run_once: true

- name: Set public IP fact
  ansible.builtin.set_fact:
    server_public_ip: "{{ public_ip_reg.content }}"
  when: public_ip_reg.content is defined

- name: Fail if public IP could not be determined
  ansible.builtin.fail:
    msg: "Could not determine the server's public IP address."
  when: server_public_ip is not defined or server_public_ip == ''

- name: Include Cloudflare DNS tasks
  ansible.builtin.include_tasks: cloudflare_dns.yml
  when: dns_provider == 'cloudflare'

- name: Generate DNS records documentation
  ansible.builtin.template:
    src: dns_records.j2
    dest: "{{ dns_records_dir }}/{{ domain_cfg.domain }}.dns"
    mode: '0644'
  vars:
    domain: "{{ domain_cfg.domain }}"
    server_ip: "{{ server_public_ip }}"
  loop: "{{ loaded_domains.results }}"
  loop_control:
    loop_var: domain_item
  vars:
    domain_cfg: "{{ domain_item.ansible_facts.domain_config }}"
  when: loaded_domains is defined and loaded_domains.results is defined

- name: Combine DNS records into single file
  ansible.builtin.shell:
    cmd: cat {{ dns_records_dir }}/*.dns > {{ dns_records_dir }}/all_domains.dns
  args:
    executable: /bin/bash
  when: loaded_domains is defined and loaded_domains.results is defined
  changed_when: false

- name: Display DNS record instructions
  debug:
    msg:
      - "DNS records have been generated for all domains."
      - "You can find the complete DNS records at: {{ dns_records_dir }}/all_domains.dns"
      - "Individual domain DNS records are in: {{ dns_records_dir }}/<domain>.dns"
      - "Please ensure these records are properly configured in your DNS provider."

---
# DNS Management role main tasks

- name: Include Cloudflare DNS management
  ansible.builtin.include_tasks: cloudflare_dns.yml
  when: dns_provider == "cloudflare"

# Placeholder for future DNS providers
# - name: Include AWS Route53 DNS management
#   ansible.builtin.include_tasks: route53_dns.yml
#   when: dns_provider == "route53"