---
- name: Deploy and Configure Mailu Multi-Domain Server
  hosts: mail_server
  become: true
  vars_files:
    - ../vault/secrets.yml # Load vaulted secrets

  roles:
    # System preparation and security
    - role: common
      tags: [common, base]
    - role: hardening
      tags: [hardening, security]
    - role: firewall
      tags: [firewall, security]
    - role: docker_base
      tags: [docker, base]
    - role: crowdsec
      tags: [crowdsec, security]
    # Infrastructure and application
    - role: dns_management
      tags: [dns, cloudflare]
    - role: traefik
      tags: [traefik, proxy, tls]
    - role: mail_security
      tags: [mail_security, dkim, spf, dmarc]
    - role: mailu
      tags: [mailu, app]
    # Optional/roadmap roles
    - role: backup
      tags: [backup]
    - role: monitoring
      tags: [monitoring]
    - role: health_check
      tags: [health, check]
