---
# Default values for docker_base role
#
# All variables are documented with type, default, and description as required by the style guide.

# Docker installation method ("package" or "script")
# Type: string
# Default: "package"
docker_install_method: "package"

# List of Docker package names to install
# Type: list
docker_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-compose-plugin

# Name of the Docker service
# Type: string
docker_service_name: "docker"

# Users to add to the docker group
# Type: list
docker_users:
  - "{{ ansible_user }}"

# Docker daemon configuration options
# Type: dict
docker_daemon_options:
  log-driver: "json-file"
  log-opts:
    max-size: "100m"
    max-file: "3"
  storage-driver: "overlay2"
  iptables: true
  live-restore: true

# Docker Compose version to install (MUST be pinned for production)
# Type: string
# Example: "2.21.0"
docker_compose_version: "2.21.0"

# Docker network configuration
# Type: list
docker_networks:
  - name: "traefik-public"
    driver: "bridge"
    attachable: true
    ipam_config:
      - subnet: "172.28.0.0/16"
        gateway: "172.28.0.1"

# Directory for Docker storage
# Type: string
docker_data_dir: "/var/lib/docker"

# Enable Docker system prune cron job
# Type: boolean
docker_enable_autoclean: true

# Cron schedule for Docker autoclean (in cron syntax)
# Type: string
docker_autoclean_schedule: "0 2 * * 0"

# Options for Docker autoclean command
# Type: string
docker_autoclean_options: "--all --volumes --force"

# Testing Guidelines:
# 1. Run with --check first: ansible-playbook site.yml --check
# 2. Verify idempotence: run twice, second run should report no changes
# 3. Validate: ensure Docker and Compose are installed and running